UNITS_MAP = {
    'net_radiation': (r'$\mathregular{R_n}$', r'$\mathregular{(W\/m^{-2}_{ground})}$'),
    'net_longwave_radiation': (r'$\mathregular{R_{0,\/lw}}}$', r'$\mathregular{(W\/m^{-2}_{ground})}$'),
    'sensible_heat_flux': ('H', r'$\mathregular{(W\/m^{-2}_{ground})}$'),
    'total_penman_monteith_evaporative_energy': (r'$\mathregular{\lambda E}$', r'$\mathregular{(W\/m^{-2}_{ground})}$'),
    'latent_heat_flux': (r'$\mathregular{\lambda E}$', r'$\mathregular{(W\/m^{-2}_{ground})}$'),
    'soil_heat_flux': ('G', r'$\mathregular{(W\/m^{-2}_{ground})}$'),
    'energy_balance': ('balance', r'$\mathregular{(W\/m^{-2}_{ground})}$'),
    'richardson_number': ('Ri', '(-)'),
    'stability_correction_for_momentum': (r'$\mathregular{\Phi_m}$', '(m)'),
    'stability_correction_for_heat': (r'$\mathregular{\Phi_h}$', '(m)'),
    'monin_obukhov_length': ('L', '(m)'),
    'available_energy': ('A', r'$\mathregular{(W\/m^{-2}_{ground})}$'),
    'penman_monteith_evaporative_energy': (r'$\mathregular{\lambda E}$', r'$\mathregular{(W\/m^{-2}_{ground})}$'),
    'boundary_resistance': (r'$\mathregular{r_a}$', r'$\mathregular{(h\/m^{-1})}$'),
    'aerodynamic_resistance': (r'$\mathregular{r_{a,\/0}}$', r'$\mathregular{(h\/m^{-1})}$'),
    'PAR_direct': r'$\mathregular{R_{inc,\/PAR,\/direct}}$',
    'PAR_diffuse': r'$\mathregular{R_{inc,\/PAR,\/diffuse}}$',
    'LAI': (r'$\mathregular{L_t}$', r'$\mathregular{(m^{2}_{leaf}\/m^{-2}_{ground})}$'),
    'surface_conductance': (r'$\mathregular{g_{s,\/l}}$', r'$\mathregular{(m\/h^{-1})}$'),
    'incident_par': (r'$\mathregular{R_{inc}}$', r'$\mathregular{(W_{PAR}\/m^{-2}_{ground})}$'),
    'incident_par_direct': (r'$\mathregular{R_{inc,\/direct}}$', r'$\mathregular{(W_{PAR}\/m^{-2}_{ground})}$'),
    'incident_par_diffuse': (r'$\mathregular{R_{inc,\/diffuse}}$', r'$\mathregular{(W_{PAR}\/m^{-2}_{ground})}$'),
    'absorbed_par': (r'$\mathregular{R_{abs}}$', r'$\mathregular{(W_{PAR}\/m^{-2}_{ground})}$'),
    'absorbed_par_soil': (r'$\mathregular{R_{abs, soil}}$', r'$\mathregular{(W_{PAR}\/m^{-2}_{ground})}$'),
    'absorbed_par_veg': (r'$\mathregular{R_{abs, veg}}$', r'$\mathregular{(W_{PAR}\/m^{-2}_{ground})}$'),
    'shaded_fraction': (r'$\mathregular{\phi_{shaded}}$', '(-)'),
    'wind_speed': ('u', r'$\mathregular{(m\/s^{-1})}$'),
    'vapor_pressure_deficit': (r'$\mathregular{D_m}$', '(kPa)'),
    'temperature': (r'$\mathregular{T_s}$', '(°C)'),
    'temperature_air': (r'$\mathregular{T_{air}}}$', '(°C)'),
    'temperature_soil': (r'$\mathregular{T_{soil}}}$', '(°C)'),
    'temperature_source': (r'$\mathregular{T_m}$', '(°C)'),
    'temperature_canopy': (r'$\mathregular{T_{can}}$', '(°C)'),
    'temperature_sunlit': (r'$\mathregular{T_{sunlit}}$', '(°C)'),
    'temperature_shaded': (r'$\mathregular{T_{shaded}}$', '(°C)'),
    'soil_water_potential': (r'$\mathregular{\Psi_{soil}}}$', '(MPa)'),
    'hour': ('hour',),
    'height': (r'$\mathregular{z_h}$', r'$\mathregular{(m)}$'),
    'gai': ('GAI', r'$\mathregular{(m^2_{leaf}\/m^{-2}_{ground})}$')
}
